In [182]:
import os
import re

log_file = "experiment_log_0.json/experiment_log.json"
# Check if the log file exists
if not os.path.exists(log_file):
    print(f"{log_file} does not exist.")

# Read the logs and extract accuracies
with open(log_file, "r") as file:
    log_text = file.read()

In [183]:
print(log_text)

Starting Flower ServerApp, config: num_rounds=3, no round_timeout

[INIT]
Using initial global parameters provided by strategy
Starting evaluation of initial global parameters
Evaluation returned no results (`None`)

[ROUND 1]
configure_fit: strategy sampled 5 clients (out of 5)
Initialising: RayBackend
Backend config: {'init_args': {'logging_level': 30, 'log_to_driver': True}, 'client_resources': {'num_cpus': 2, 'num_gpus': 0}, 'actor': {'tensorflow': 0}}
Constructed ActorPool with: 4 actors
Using InMemoryState
aggregate_fit: received 5 results and 0 failures
configure_evaluate: strategy sampled 5 clients (out of 5)
aggregate_evaluate: received 5 results and 0 failures
{"avr_accuracy": 0.5628228628561907}

[ROUND 2]
configure_fit: strategy sampled 5 clients (out of 5)
aggregate_fit: received 5 results and 0 failures
configure_evaluate: strategy sampled 5 clients (out of 5)
aggregate_evaluate: received 5 results and 0 failures
{"avr_accuracy": 0.7816197300449925}

[ROUND 3]
configure_f

In [184]:

# Regular expression to match accuracy values
pattern = r"'avr_accuracy': \[(.*?)\]"

# Search for matches after '[SUMMARY]'
match = re.findall(pattern, log_text, re.DOTALL)

print(match[0])

(1, 0.5628228628561907),
	                  (2, 0.7816197300449925),
	                  (3, 0.8385269121813032)


In [185]:
import ast

runs = {}
for run in range(len(match)):
    extracted_string = match[run].strip().replace('\n', '').replace('\t', '')
    avr_accuracy_list = ast.literal_eval(f"[{extracted_string}]")
    runs[run] = avr_accuracy_list

In [186]:
runs

{0: [(1, 0.5628228628561907),
  (2, 0.7816197300449925),
  (3, 0.8385269121813032)],
 1: [(1, 0.6544742542909515),
  (2, 0.7908681886352275),
  (3, 0.8486918846858856)],
 2: [(1, 0.6385602399600067),
  (2, 0.8163639393434428),
  (3, 0.8503582736210632)],
 3: [(1, 0.47658723546075654), (2, 0.786535577403766), (3, 0.841193134477587)],
 4: [(1, 0.7037160473254458), (2, 0.798366938843526), (3, 0.8434427595400766)],
 5: [(1, 0.36293951008165304),
  (2, 0.8054490918180304),
  (3, 0.8421929678386936)],
 6: [(1, 0.5749875020829862),
  (2, 0.7940343276120646),
  (3, 0.8373604399266789)],
 7: [(1, 0.596817197133811), (2, 0.7884519246792201), (3, 0.8369438426928845)],
 8: [(1, 0.6321446425595734),
  (2, 0.7675387435427429),
  (3, 0.8400266622229628)],
 9: [(1, 0.4201799700049992),
  (2, 0.7954507582069655),
  (3, 0.8344442592901183)],
 10: [(1, 0.6380603232794534),
  (2, 0.8016997167138811),
  (3, 0.8294450924845859)],
 11: [(1, 0.42492917847025496),
  (2, 0.8080319946675554),
  (3, 0.84085985669

In [187]:
import numpy as np
# Transform to a NumPy array
# Extract the second values only
array = np.array([
    [value[1] for value in values]
    for values in runs.values()
])

print(array)

[[0.56282286 0.78161973 0.83852691]
 [0.65447425 0.79086819 0.84869188]
 [0.63856024 0.81636394 0.85035827]
 [0.47658724 0.78653558 0.84119313]
 [0.70371605 0.79836694 0.84344276]
 [0.36293951 0.80544909 0.84219297]
 [0.5749875  0.79403433 0.83736044]
 [0.5968172  0.78845192 0.83694384]
 [0.63214464 0.76753874 0.84002666]
 [0.42017997 0.79545076 0.83444426]
 [0.63806032 0.80169972 0.82944509]
 [0.42492918 0.80803199 0.84085986]
 [0.4301783  0.80644893 0.84010998]
 [0.47075487 0.7952008  0.83752708]
 [0.43051158 0.79370105 0.83527745]
 [0.63947675 0.80053324 0.84252625]
 [0.65947342 0.8191968  0.84352608]
 [0.61789702 0.78570238 0.83611065]
 [0.68555241 0.80536577 0.85119147]
 [0.60089985 0.81003166 0.83511081]
 [0.45909015 0.78486919 0.84127645]
 [0.43884353 0.80019997 0.83186136]
 [0.6353941  0.77987002 0.83902683]
 [0.45450758 0.79811698 0.84685886]
 [0.52966172 0.81428095 0.85044159]
 [0.58298617 0.80053324 0.84594234]
 [0.70929845 0.80511581 0.84435927]
 [0.47758707 0.80328279 0.84

In [188]:
array.mean(axis=0)

array([0.53179053, 0.79506416, 0.84088819])